# Generated by Django 5.0.4 on 2024-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_autenticacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
