# Generated by Django 5.0.4 on 2024-04-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_user_token_autenticacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre_usuario',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
