# Generated by Django 5.0.4 on 2024-04-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_product_stock_stockcharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
