# Generated by Django 5.0.4 on 2024-04-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_ventas_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCharge',
        ),
    ]
