# Generated by Django 5.0.4 on 2024-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo_producto',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
