# Generated by Django 5.0.4 on 2024-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_product_codigo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
