# Generated by Django 5.0.4 on 2024-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_product_codigo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='control_stock',
            field=models.IntegerField(default=0),
        ),
    ]
