# Generated by Django 5.0.4 on 2024-05-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_product_control_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='control_stock_venta',
            field=models.IntegerField(default=0),
        ),
    ]
