# Generated by Django 5.0.4 on 2024-05-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_ventas_control_stock_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='control_stock_venta',
        ),
        migrations.AlterField(
            model_name='product',
            name='control_stock',
            field=models.IntegerField(),
        ),
    ]
