# Generated by Django 5.0.4 on 2024-05-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_ventas_control_stock_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='control_stock',
            field=models.BooleanField(default=True),
        ),
    ]
