# Generated by Django 5.0.4 on 2024-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_rename_vendedor_ventas_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cliente',
        ),
    ]
