# Generated by Django 5.0.4 on 2024-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_tarjetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetas',
            name='id_venta',
        ),
    ]
