# Generated by Django 5.0.4 on 2024-05-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_remove_tarjetas_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
