# Generated by Django 5.0.4 on 2024-05-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_tarjetas_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='monto',
            field=models.CharField(max_length=10000000000),
        ),
    ]
