# Generated by Django 5.0.4 on 2024-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_alter_tarjetas_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
